CREATE TABLE STUDENT1 (
 ROLL_NO TEXT PRIMARY KEY,
 NAME TEXT NOT NULL,
 ADDRESS TEXT,
 PHONE TEXT,
 AGE INTEGER
 );


INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
 ('1', 'USHER', 'SHANNON', '*****', 14),
 ('2', 'JETHRO', 'LUCKY', '*****', 14),
 ('3', 'JOSH', 'FRED', '*****' , 13),
 ('4', 'CATEE', 'SHANNON', '*****' , 14),
 ('5', 'CHRIS', 'FRED', '*****' , 13),
 ('6', 'HARRY', 'LUCKY', '*****' , 14);


SELECT * FROM STUDENT1;

SELECT * FROM STUDENT1 WHERE AGE = 14 AND ADDRESS = 'SHANNON';

SELECT * FROM STUDENT1 WHERE AGE = 14 AND NAME = 'USHER';

SELECT * FROM STUDENT1 WHERE NAME = 'USHER' OR NAME = 'JOSH';

SELECT * FROM STUDENT1 WHERE NAME = 'USHER' OR AGE = 13;

SELECT * FROM STUDENT1 WHERE AGE = 14 AND (NAME = 'USHER' OR NAME = 'JETHRO');