CREATE TABLE IF NOT EXISTS PRODUCTS (
 PRODUCT_ID TEXT,
 PRODUCT_NAME TEXT,
 SUPPLIER_ID TEXT,
 CATEGORY_ID TEXT,
 UNIT TEXT,
 PRICE REAL 
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
 ('1', 'BAGS', '1', '1', '20 BOXES*40 BAGS', 40),
 ('2', 'JUST JUICE', '1', '1', '48 - 24 OZ BOTTLES', 10),
 ('3', 'SLIME', '1', '2', '12-225 ML BOTTLES', 15),
 ('4', 'CHICKEN SALT', '2', '2', '2', '48- 6 OZ JARS', 22),
 ('5', 'LEMON MIX', '2', '2', '36 BOXES', 21.35);

SELECT COUNT(PRODUCT_ID) AS product_count
FROM PRODUCTS;


SELECT AVG(PRICE) AS average_price
FROM PRODUCTS;

SELECT SUM(PRICE) AS total_price
FROM PRODUCTS;
SELECT MAX(PRICE) AS maximum_price
FROM PRODUCTS;
SELECT MIN(PRICE) AS minimum_price
FROM PRODUCTS;